### ISSUE TITLE
Counting backlogs and updating as soon as they are cleared.

### ISSUE THREAD

**Issue by AIEnthusias-t** [ankushgarg1998/ipu-ranklist#19] opened 2019-10-11 18:04 UTC

**Comment by ankushgarg1998** [comment] 2019-10-16 21:46
Hi @AIEnthusias-t 
Your Issue is duplicate of #16 

So, I'm modifying it a little.

**Comment by ankushgarg1998** [comment] 2019-10-16 21:48
- [ ] Counting semester-wise and overall backlogs.
- [ ] Displaying them in the profile and ranklist section.
- [ ] Updating them, when cleared.

**Comment by ankushgarg1998** [comment] 2020-03-16 06:47
Fixed.
Subject marks show a 'backlog' tag and that tag is removed, when backlog is cleared.
@AIEnthusias-t

**Closed by ankushgarg1998** 2020-03-16 06:47 UTC
Labels: feature, major-update
